# Generated by Django 2.1.2 on 2018-10-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='test',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='test'),
        ),
    ]
