# Generated by Django 2.1.2 on 2018-10-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181024_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insiderrecord',
            name='close',
        ),
        migrations.RemoveField(
            model_name='insiderrecord',
            name='high',
        ),
        migrations.RemoveField(
            model_name='insiderrecord',
            name='low',
        ),
        migrations.RemoveField(
            model_name='insiderrecord',
            name='open',
        ),
        migrations.RemoveField(
            model_name='insiderrecord',
            name='volume',
        ),
        migrations.AddField(
            model_name='insider',
            name='owner_type',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='Owner type'),
        ),
        migrations.AddField(
            model_name='insider',
            name='relation',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='Relation'),
        ),
        migrations.AddField(
            model_name='insiderrecord',
            name='last_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Last price'),
        ),
        migrations.AddField(
            model_name='insiderrecord',
            name='shares_held',
            field=models.FloatField(blank=True, null=True, verbose_name='Shares held'),
        ),
        migrations.AddField(
            model_name='insiderrecord',
            name='shares_traded',
            field=models.FloatField(blank=True, null=True, verbose_name='Shares traded'),
        ),
    ]
